---
- name: Install base development packages
  ansible.builtin.package:
    name:
      - base-devel
      - git
    state: present
  become: true

- name: Check if yay is installed
  ansible.builtin.command: which yay
  register: yay_check
  failed_when: false
  changed_when: false

- name: Clone yay repository
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    clone: true
    update: true
  when: yay_check.rc != 0
  become: false

- name: Build and install yay
  ansible.builtin.command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  when: yay_check.rc != 0
  become: false

- name: Clean up yay build directory
  ansible.builtin.file:
    path: /tmp/yay
    state: absent
  when: yay_check.rc != 0
  become: true

- name: Install base packages via pacman
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present
  become: true
  when: base_packages is defined and base_packages | length > 0

- name: Install AUR packages via yay
  ansible.builtin.command: yay -S --noconfirm {{ item }}
  loop: "{{ aur_packages }}"
  become: false
  become_user: "{{ user_name }}"
  when: aur_packages is defined and aur_packages | length > 0