---
- name: Install base development packages
  package:
    name:
      - base-devel
      - git
    state: present
  become: true

- name: Check if yay is installed
  command: which yay
  register: yay_check
  failed_when: false
  changed_when: false

- name: Clone yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    clone: true
    update: true
  when: yay_check.rc != 0
  become: false

- name: Build and install yay
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  when: yay_check.rc != 0
  become: false

- name: Clean up yay build directory
  file:
    path: /tmp/yay
    state: absent
  when: yay_check.rc != 0
  become: true