---
- name: Install required packages
  ansible.builtin.package:
    name:
      - sudo
      - zsh
    state: present
  become: true

- name: Ensure wheel group exists
  ansible.builtin.group:
    name: wheel
    state: present
  become: true

- name: Create user {{ user_name }}
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ user_shell }}"
    groups: "{{ user_groups }}"
    append: true
    home: "{{ user_home }}"
    create_home: "{{ create_home }}"
    state: present
  become: true

- name: Configure sudo for wheel group
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
  become: true
  when: not sudo_nopasswd

- name: Configure passwordless sudo for wheel group
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true
  when: sudo_nopasswd

- name: Ensure user home directory permissions
  ansible.builtin.file:
    path: "{{ user_home }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'
    state: directory
  become: true

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'
    state: directory
  become: true

- name: Generate SSH key pair (Ed25519)
  community.crypto.openssh_keypair:
    path: "{{ user_home }}/.ssh/id_ed25519"
    type: ed25519
    passphrase: "{{ ssh_key_passphrase }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'
    state: present
  become: true
