galaxy_info:
  author: cuiv
  description: Role to manage user accounts and sudo access
  company: Personal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - user
    - sudo
    - security

dependencies: []