---
- name: Install GitHub CLI via pacman
  ansible.builtin.package:
    name: github-cli
    state: present
  become: true

- name: Check if GitHub CLI is authenticated
  ansible.builtin.command: gh auth status
  register: gh_auth_status
  failed_when: false
  changed_when: false
  become: false
  become_user: "{{ user_name }}"

- name: Authenticate with GitHub using personal access token
  ansible.builtin.shell: |
    echo "{{ vault_github_token }}" | gh auth login --with-token
  when: gh_auth_status.rc != 0
  become: false
  become_user: "{{ user_name }}"
  # no_log: true

- name: Check if SSH key already exists on GitHub
  ansible.builtin.command: gh ssh-key list
  register: existing_ssh_keys
  changed_when: false
  become: false
  become_user: "{{ user_name }}"

- name: Read SSH public key
  ansible.builtin.slurp:
    src: "{{ user_home }}/.ssh/id_ed25519.pub"
  register: ssh_public_key
  become: false

- name: Parse SSH public key content
  ansible.builtin.set_fact:
    ssh_key_content: "{{ ssh_public_key.content | b64decode | trim }}"

- name: Check if current SSH key is already uploaded
  ansible.builtin.set_fact:
    ssh_key_exists: "{{ ssh_key_content.split()[1] in existing_ssh_keys.stdout }}"

- name: Upload SSH key to GitHub
  ansible.builtin.command: >
    gh ssh-key add {{ user_home }}/.ssh/id_ed25519.pub
    --title "{{ github_ssh_key_title }}"
    --type "{{ github_ssh_key_type }}"
  when: not ssh_key_exists
  become: false
  become_user: "{{ user_name }}"

- name: Configure Git to use SSH for GitHub
  ansible.builtin.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - name: url.git@github.com:.insteadOf
      value: https://github.com/
  become: false
  become_user: "{{ user_name }}"

- name: Test SSH connection to GitHub
  ansible.builtin.command: ssh -T git@github.com
  register: github_ssh_test
  failed_when: github_ssh_test.rc not in [0, 1]  # GitHub returns 1 on successful auth
  changed_when: false
  become: false
  become_user: "{{ user_name }}"
