---
# Dependencies for dotfiles and other tools
dependency_packages:
  - stow
  - zoxide
  - starship
  - fzf
  - eza
  - neovim
  - tmux
  - bat
  - ripgrep

# AUR dependencies
dependency_aur_packages: []