---
- name: Install dependency packages
  ansible.builtin.package:
    name: "{{ dependency_packages }}"
    state: present
  become: true

- name: Check if AUR dependency packages are already installed
  ansible.builtin.command: yay -Q {{ item }}
  loop: "{{ dependency_aur_packages }}"
  register: dependency_aur_package_check
  failed_when: false
  changed_when: false
  become: false
  when: dependency_aur_packages is defined and dependency_aur_packages | length > 0

- name: Install AUR dependency packages via yay
  ansible.builtin.command: yay -S --noconfirm {{ item.item }}
  loop: "{{ dependency_aur_package_check.results }}"
  become: false
  when: 
    - dependency_aur_packages is defined and dependency_aur_packages | length > 0
    - item.rc != 0

- name: Check if oh-my-zsh is already installed
  ansible.builtin.stat:
    path: "/home/{{ user_name }}/.oh-my-zsh"
  register: ohmyzsh_check
  become: false

- name: Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become: false
  when: not ohmyzsh_check.stat.exists

- name: Create zsh plugins directory
  ansible.builtin.file:
    path: "/home/{{ user_name }}/.config/zsh/plugins"
    state: directory
    mode: '0755'
  become: false

- name: Clone zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ user_name }}/.config/zsh/plugins/zsh-autosuggestions"
    clone: true
    update: true
  become: false

- name: Clone zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ user_name }}/.config/zsh/plugins/zsh-syntax-highlighting"
    clone: true
    update: true
  become: false

- name: Clone zsh-vi-mode plugin
  ansible.builtin.git:
    repo: https://github.com/jeffreytse/zsh-vi-mode.git
    dest: "/home/{{ user_name }}/.config/zsh/plugins/zsh-vi-mode"
    clone: true
    update: true
  become: false

- name: Create tmux plugins directory
  ansible.builtin.file:
    path: "/home/{{ user_name }}/.config/tmux/plugins"
    state: directory
    mode: '0755'
  become: false

- name: Clone tmux plugin manager (TPM)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ user_name }}/.config/tmux/plugins/tpm"
    clone: true
    update: true
  become: false